-- administrator. 테이블스페이스 생성, bookuser라는 유저생성, 접속을 위한 DBA권한부여

CREATE TABLESPACE bookuser DATAFILE '/bizwork/oracle/data/bookuser.dbf' SIZE 1M AUTOEXTEND ON NEXT 1K;
CREATE USER bookuser IDENTIFIED BY 1234 DEFAULT TABLESPACE bookuser;
GRANT DBA TO bookuser;

-- bookuser. tbl_books, tbl_member, tbl_read_book 테이블 생성, seq_read_book 시퀀스 생성, 외래키 생성

CREATE TABLE tbl_books(
B_CODE	VARCHAR2(20)		PRIMARY KEY,
B_NAME	nVARCHAR2(125)	NOT NULL	,
B_AUTHER	nVARCHAR2(125)	NOT NULL	,
B_COMP	nVARCHAR2(125)		,
B_YEAR	VARCHAR2(10)		,
B_IPRICE	NUMBER		
);

CREATE TABLE tbl_member(
M_ID	VARCHAR2(20)	NOT NULL	PRIMARY KEY,
M_PASSWORD	nVARCHAR2(125)	NOT NULL	,
M_LOGIN_DATE	VARCHAR2(10)		,
M_REM	nVARCHAR2(125)		
);

CREATE TABLE tbl_read_book(
RB_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
RB_BCODE	VARCHAR2(20)	NOT NULL	,
RB_DATE	VARCHAR2(10)	NOT NULL	,
RB_STIME	VARCHAR2(10)		,
RB_RTIME	NUMBER(10,3)		,
RB_SUBJECT	nVARCHAR2(20)		,
RB_TEXT	nVARCHAR2(400)		,
RB_STAR	NUMBER		
);

CREATE SEQUENCE seq_read_book
START WITH 1 INCREMENT BY 1;

ALTER TABLE tbl_read_book -- 연동되는 테이블
ADD CONSTRAINT FK_BOOKS
FOREIGN KEY(rb_bcode) -- PK키와 연동되는 테이블의 컬럼
REFERENCES tbl_books(b_code); -- PK키로 설정된 것. n:1에서 1 쪽의 컬럼